(dp1
S'output'
p2
S"<class '_mysql_exceptions.OperationalError'> (1701, 'Cannot truncate a table referenced in a foreign key constraint (`UseresDB`.`auth_permission`, CONSTRAINT `auth_permission_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `UseresDB`.`auth_group` (`id`))')"
p3
sS'layer'
p4
S'/home/adrian/web2py/applications/CygnusCloud/models/db.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\nfrom configuration import DBConfigurator\nfrom gluon.tools import Auth\n\nconf = DBConfigurator('170590ucm')\nconf.createDatabase('UseresDB')\n#conf.addUser('CygnusCloud','cygnuscloud2012', 'UserDB')\nuserDB = DAL('mysql://CygnusCloud:cygnuscloud2012@localhost/UseresDB',migrate_enabled=True, pool_size=0)\n\n\n# Autentication\n\nauth = Auth(userDB)\nauth.define_tables(migrate = True)\n\n#Borramos basura\n\nuserDB.auth_membership.truncate()\nuserDB.auth_event.truncate()\nuserDB.auth_cas.truncate()\nuserDB.auth_group.truncate()\nuserDB.auth_user.truncate()\nuserDB.auth_permission.truncate()\n\nuserDB.auth_user.email.requires = IS_NOT_IN_DB(userDB, userDB.auth_user.email)\n\n\n\n\nuserDB.define_table('UserGroup',\n   Field('yearGroup','integer', 'reference Users'),\n   Field('cod','integer','reference subjects'),\n   Field('curse','integer'),\n   Field('curseGroup', length=1),\n   primarykey=['cod','curseGroup'],migrate= True)\n\nuserDB.define_table('ClassGroup',\n   Field('userId','integer', 'reference auth_user' ),\n   Field('cod','integer','reference UserGroup'),\n   Field('curseGroup','reference UserGroup',length=1 ),\n   primarykey=['cod','curseGroup','userId'],migrate= True)\n\nuserDB.define_table('Subjects',\n   Field('code','integer'),\n   Field('name',length=15),migrate= True)\n\n\n\nuserDB.define_table('VMByGroup',\n   Field('VMName',length=20),\n   Field('cod','integer','reference UserGroup'),\n   Field('curseGroup','reference UserGroup',length=1 ),\n   primarykey=['cod','curseGroup','VMName'],migrate= True)\n\n#Usuario de prueba\n#u1 = userDB.auth_user.insert(password = userDB.auth_user.password.validate('1234')[0],email = 'Admin1@ucm.es',first_name='Bertoldo',last_name='Pedralbes')\n#A\xc3\xb1adimos los grupos\n#auth.add_group('Student', 'Only run virtual machines available')\n#auth.add_group('Administrator', 'All privilages available')\n#Enlazamos los usuarios a los grupos\n#auth.add_membership('Administrator',u1)\nprint userDB.tables\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/adrian/web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "/home/adrian/web2py/applications/CygnusCloud/models/db.py", line 21, in <module>\n    userDB.auth_group.truncate()\n  File "/home/adrian/web2py/gluon/dal.py", line 7968, in truncate\n    return self._db._adapter.truncate(self, mode)\n  File "/home/adrian/web2py/gluon/dal.py", line 1367, in truncate\n    self.execute(query)\n  File "/home/adrian/web2py/gluon/dal.py", line 1709, in execute\n    return self.log_execute(*a, **b)\n  File "/home/adrian/web2py/gluon/dal.py", line 1703, in log_execute\n    ret = self.cursor.execute(*a, **b)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute\n    self.errorhandler(self, exc, value)\n  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1701, \'Cannot truncate a table referenced in a foreign key constraint (`UseresDB`.`auth_permission`, CONSTRAINT `auth_permission_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `UseresDB`.`auth_group` (`id`))\')\n'
p11
s.